version: 1
builder:
  configs:
    - platform: macos-spm
      scheme: AgentRuntimeCore
    - platform: macos-spm
      scheme: AgentRuntimeFileMemory
    - platform: ios
      scheme: AgentRuntimeApple
    - platform: watchos
      scheme: AgentRuntimeApple
    - platform: tvos
      scheme: AgentRuntimeApple
